# Generated by Django 2.1.3 on 2022-07-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_and_brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
